# Generated by scripts/homebrew.sh — edit that, not this.
cask "tint-app" do
  version "0.6.1"
  sha256 "fba69d953a5a8431909810b078d6f35822bd407a3edb8792f2a4f3d83de7df5d"

  url "https://github.com/duma799/tint/releases/download/v0.6.1/Tint-#{version}-macos.zip"
  name "Tint"
  desc "Pick a wallpaper, preview its colour scheme, tweak it and apply it"
  homepage "https://github.com/duma799/tint"

  depends_on macos: ">= :sequoia"

  app "Tint.app"

  # The app is signed ad hoc, not with a paid Developer ID, so macOS would
  # refuse to open a downloaded copy. Homebrew verified the checksum above.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Tint.app"]
  end

  zap trash: "~/.config/tint/settings.json"
end
