# Generated by scripts/homebrew.sh — edit that, not this.
cask "tint-app" do
  version "0.7.0"
  sha256 "f75162b267dab9227f8f2572ecee8e751ebdac089b785ab0c4014ca428c923eb"

  url "https://github.com/duma799/tint/releases/download/v0.7.0/Tint-#{version}-macos.zip"
  name "Tint"
  desc "Pick a wallpaper, preview its colour scheme, tweak it and apply it"
  homepage "https://github.com/duma799/tint"

  depends_on macos: ">= :sequoia"

  app "Tint.app"

  # Unless the release was signed with a Developer ID and notarized, the app
  # is signed ad hoc and macOS would refuse to open a downloaded copy.
  # Homebrew verified the checksum above; for a notarized app this is a no-op.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Tint.app"]
  end

  zap trash: "~/.config/tint/settings.json"
end
