# Generated by scripts/homebrew.sh — edit that, not this.
cask "tint-app" do
  version "0.5.0"
  sha256 "353e96b787fda455378d4b7c7dbe5599f5f7d8dc90128c3a0de208fb862b48fc"

  url "https://github.com/duma799/tint/releases/download/v0.5.0/Tint-#{version}-macos.zip"
  name "Tint"
  desc "Pick a wallpaper, preview its colour scheme, tweak it and apply it"
  homepage "https://github.com/duma799/tint"

  depends_on macos: ">= :sonoma"

  app "Tint.app"

  # The app is signed ad hoc, not with a paid Developer ID, so macOS would
  # refuse to open a downloaded copy. Homebrew verified the checksum above.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Tint.app"]
  end

  zap trash: "~/.config/tint/settings.json"
end
