using System.Text;
using System.Text.Json;
using Tint.Core.Colors;
using Tint.Core.Themes;

namespace Tint.Core.Output;

/// <summary>
/// Writes the files pywal writes to <c>~/.cache/wal</c>, in pywal's formats,
/// so everything that reads them — SketchyBar and JankyBorders configs,
/// Neovim (pywal.nvim), kitty, shell scripts — works with tint unchanged.
/// </summary>
public static class PywalWriter
{
    public sealed record Result(IReadOnlyList<string> Written, IReadOnlyList<string> Warnings);

    public static Result Write(Scheme scheme, string wallpaper, string cacheDirectory, string? templatesDirectory)
    {
        Directory.CreateDirectory(cacheDirectory);
        var written = new List<string>();
        var warnings = new List<string>();

        void Save(string name, string content)
        {
            string path = Path.Combine(cacheDirectory, name);
            AtomicWrite(path, content);
            written.Add(path);
        }

        Save("wal", wallpaper);
        Save("colors", string.Concat(scheme.Colors.Select(c => c.Hex + "\n")));
        Save("colors.json", Json(scheme, wallpaper));
        Save("colors.sh", Shell(scheme, wallpaper));
        Save("colors.css", Css(scheme, wallpaper));
        Save("colors-kitty.conf", Kitty(scheme));
        Save("colors-wal.vim", Vim(scheme, wallpaper));

        // User templates: ~/.config/wal/templates/<name> → ~/.cache/wal/<name>.
        if (templatesDirectory is not null && Directory.Exists(templatesDirectory))
        {
            foreach (string template in Directory.EnumerateFiles(templatesDirectory).Order(StringComparer.Ordinal))
            {
                string name = Path.GetFileName(template);
                TemplateRenderer.Result rendered = TemplateRenderer.Render(File.ReadAllText(template), scheme, wallpaper);
                Save(name, rendered.Text);
                warnings.AddRange(rendered.Unknown.Distinct().Select(u => $"{name}: left {u} as is (not a known placeholder)"));
            }
        }

        return new Result(written, warnings);
    }

    /// <summary>
    /// Write to a temp file and rename over the target, so a program reading
    /// the file at the wrong moment sees the old or the new version, never half.
    /// </summary>
    private static void AtomicWrite(string path, string content)
    {
        string temp = $"{path}.tint-{Environment.ProcessId}.tmp";
        File.WriteAllText(temp, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        File.Move(temp, path, overwrite: true);
    }

    /// <summary>
    /// Escapes a value for a double-quoted Vimscript string. Backslash first,
    /// so the escapes added after it aren't doubled; line breaks as \n / \r so
    /// a strange filename can't end the string and start a new command.
    /// </summary>
    internal static string VimString(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal);

    /// <summary>
    /// Escapes a value for a double-quoted CSS string: backslash first, then
    /// quotes; line breaks as CSS hex escapes (a raw newline is invalid there).
    /// </summary>
    internal static string CssString(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\n", "\\A ", StringComparison.Ordinal)
        .Replace("\r", "\\D ", StringComparison.Ordinal);

    private static IEnumerable<(string Name, Rgb Color)> Numbered(Scheme scheme) =>
        scheme.Colors.Select((c, i) => ($"color{i}", c));

    private static string Json(Scheme scheme, string wallpaper)
    {
        using var stream = new MemoryStream();
        using (var json = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            json.WriteStartObject();
            json.WriteString("wallpaper", wallpaper);
            json.WriteString("alpha", "100");
            json.WriteStartObject("special");
            json.WriteString("background", scheme.Background.Hex);
            json.WriteString("foreground", scheme.Foreground.Hex);
            json.WriteString("cursor", scheme.Cursor.Hex);
            json.WriteEndObject();
            json.WriteStartObject("colors");
            foreach ((string name, Rgb color) in Numbered(scheme))
            {
                json.WriteString(name, color.Hex);
            }

            json.WriteEndObject();
            json.WriteEndObject();
        }

        return Encoding.UTF8.GetString(stream.ToArray()) + "\n";
    }

    private static string Shell(Scheme scheme, string wallpaper)
    {
        var sb = new StringBuilder();
        sb.Append("# Shell variables\n# Generated by tint (pywal-compatible)\n");
        sb.Append($"wallpaper='{wallpaper.Replace("'", "'\\''", StringComparison.Ordinal)}'\n\n");
        sb.Append($"# Special\nbackground='{scheme.Background.Hex}'\nforeground='{scheme.Foreground.Hex}'\ncursor='{scheme.Cursor.Hex}'\n\n");
        sb.Append("# Colors\n");
        foreach ((string name, Rgb color) in Numbered(scheme))
        {
            sb.Append($"{name}='{color.Hex}'\n");
        }

        return sb.ToString();
    }

    private static string Css(Scheme scheme, string wallpaper)
    {
        var sb = new StringBuilder();
        sb.Append("/* CSS variables\n   Generated by tint (pywal-compatible) */\n:root {\n");
        sb.Append($"    --wallpaper: url(\"{CssString(wallpaper)}\");\n\n");
        sb.Append($"    /* Special */\n    --background: {scheme.Background.Hex};\n    --foreground: {scheme.Foreground.Hex};\n    --cursor: {scheme.Cursor.Hex};\n\n");
        sb.Append("    /* Colors */\n");
        foreach ((string name, Rgb color) in Numbered(scheme))
        {
            sb.Append($"    --{name}: {color.Hex};\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string Kitty(Scheme scheme)
    {
        var sb = new StringBuilder();
        sb.Append($"foreground         {scheme.Foreground.Hex}\n");
        sb.Append($"background         {scheme.Background.Hex}\n");
        sb.Append($"cursor             {scheme.Cursor.Hex}\n");
        sb.Append($"selection_foreground {scheme.Background.Hex}\n");
        sb.Append($"selection_background {scheme.Foreground.Hex}\n\n");
        sb.Append($"active_tab_foreground   {scheme.Background.Hex}\n");
        sb.Append($"active_tab_background   {scheme.Foreground.Hex}\n");
        sb.Append($"inactive_tab_foreground {scheme.Foreground.Hex}\n");
        sb.Append($"inactive_tab_background {scheme.Background.Hex}\n\n");
        sb.Append($"active_border_color   {scheme[4].Hex}\n");
        sb.Append($"inactive_border_color {scheme[8].Hex}\n");
        sb.Append($"bell_border_color     {scheme[1].Hex}\n\n");
        foreach ((string name, Rgb color) in Numbered(scheme))
        {
            sb.Append($"{name,-8} {color.Hex}\n");
        }

        return sb.ToString();
    }

    private static string Vim(Scheme scheme, string wallpaper)
    {
        var sb = new StringBuilder();
        sb.Append("\" Special\n");
        sb.Append($"let wallpaper  = \"{VimString(wallpaper)}\"\n");
        sb.Append($"let background = \"{scheme.Background.Hex}\"\n");
        sb.Append($"let foreground = \"{scheme.Foreground.Hex}\"\n");
        sb.Append($"let cursor     = \"{scheme.Cursor.Hex}\"\n\n");
        sb.Append("\" Colors\n");
        foreach ((string name, Rgb color) in Numbered(scheme))
        {
            sb.Append($"let {name,-7} = \"{color.Hex}\"\n");
        }

        return sb.ToString();
    }
}
