# Generated by scripts/homebrew.sh — edit that, not this.
class Tint < Formula
  desc "Colour themes from your wallpaper, for macOS"
  homepage "https://github.com/duma799/tint"
  url "https://github.com/duma799/tint/releases/download/v0.6.0/tint-0.6.0-macos.tar.gz"
  version "0.6.0"
  sha256 "21a4c9c34ddd248df2d1b4864074ea3575deb1205dd42b2d14b6e737fb711e49"
  license "GPL-3.0-or-later"

  depends_on :macos

  def install
    bin.install "tint"
  end

  def caveats
    <<~EOS
      Theme everything on each wallpaper change, from login:
        tint service install
      Check the setup:
        tint doctor
      The app (menu bar + window):
        brew install --cask duma799/tint/tint-app
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tint --version")
  end
end
