# Generated by scripts/homebrew.sh — edit that, not this.
class Tint < Formula
  desc "Colour themes from your wallpaper, for macOS"
  homepage "https://github.com/duma799/tint"
  url "https://github.com/duma799/tint/releases/download/v0.5.0/tint-0.5.0-macos.tar.gz"
  version "0.5.0"
  sha256 "bee28b3deb0a4f90ea1320ee31ae28e2cd79481db234d14ee9ecfa9938666bc8"
  license "GPL-3.0-or-later"

  depends_on :macos

  def install
    bin.install "tint"
  end

  def caveats
    <<~EOS
      Theme everything on each wallpaper change, from login:
        tint service install
      Check the setup:
        tint doctor
      The app (menu bar + window):
        brew install --cask duma799/tint/tint-app
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tint --version")
  end
end
