# Generated by scripts/homebrew.sh — edit that, not this.
class Tint < Formula
  desc "Colour themes from your wallpaper, for macOS"
  homepage "https://github.com/duma799/tint"
  url "https://github.com/duma799/tint/releases/download/v0.6.1/tint-0.6.1-macos.tar.gz"
  version "0.6.1"
  sha256 "7ecb9ddb61fa8112f21c7129f5dbc403b629f60c875bb45c794eec66df2e9795"
  license "GPL-3.0-or-later"

  depends_on :macos

  def install
    bin.install "tint"
  end

  def caveats
    <<~EOS
      Theme everything on each wallpaper change, from login:
        tint service install
      Check the setup:
        tint doctor
      The app (menu bar + window):
        brew install --cask duma799/tint/tint-app
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tint --version")
  end
end
