#!/bin/sh
# Writes the Homebrew formula (the command) and cask (the app) for the
# release files in dist/. Run by the release workflow after packaging.
#
#   scripts/homebrew.sh 0.5.0
set -eu

version="${1:?usage: scripts/homebrew.sh <version>}"
cd "$(dirname "$0")/.."
sha() { shasum -a 256 "dist/$1" | cut -d' ' -f1; }
base="https://github.com/duma799/tint/releases/download/v$version"
mkdir -p Formula Casks

cat > Formula/tint.rb <<RUBY
# Generated by scripts/homebrew.sh — edit that, not this.
class Tint < Formula
  desc "Colour themes from your wallpaper, for macOS"
  homepage "https://github.com/duma799/tint"
  url "$base/tint-$version-macos.tar.gz"
  version "$version"
  sha256 "$(sha "tint-$version-macos.tar.gz")"
  license "GPL-3.0-or-later"

  depends_on :macos

  def install
    bin.install "tint"
  end

  def caveats
    <<~EOS
      Theme everything on each wallpaper change, from login:
        tint service install
      Check the setup:
        tint doctor
      The app (menu bar + window):
        brew install --cask duma799/tint/tint-app
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tint --version")
  end
end
RUBY

cat > Casks/tint-app.rb <<RUBY
# Generated by scripts/homebrew.sh — edit that, not this.
cask "tint-app" do
  version "$version"
  sha256 "$(sha "Tint-$version-macos.zip")"

  url "$base/Tint-#{version}-macos.zip"
  name "Tint"
  desc "Pick a wallpaper, preview its colour scheme, tweak it and apply it"
  homepage "https://github.com/duma799/tint"

  depends_on macos: ">= :sonoma"

  app "Tint.app"

  # The app is signed ad hoc, not with a paid Developer ID, so macOS would
  # refuse to open a downloaded copy. Homebrew verified the checksum above.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Tint.app"]
  end

  zap trash: "~/.config/tint/settings.json"
end
RUBY

echo "wrote Formula/tint.rb and Casks/tint-app.rb for $version"
