import Foundation

/// A theme for ApolloShell (github.com/Silvertree2010/ApolloShell): a CSS file
/// of `--apollo-*` tokens in its themes folder. ApolloShell re-reads a theme
/// when its file changes, so after choosing "tint" once in Nexus → Themes,
/// every wallpaper change re-colours the shell too.
public enum ApolloShellTheme {
    public static let fileName = "tint.css"

    public static func render(_ scheme: Scheme, wallpaper: String) -> String {
        let dark = scheme.mode == .dark
        let bg = scheme.background.lab

        // Layers step away from the background: lighter on dark themes, darker on light.
        func layer(_ step: Double) -> Rgb { bg.withLightness(min(max(bg.l + (dark ? step : -step * 0.6), 0), 100)).rgb }
        func mix(_ a: Rgb, _ b: Rgb, _ t: Double) -> Rgb {
            let x = a.lab, y = b.lab
            return Lab(l: x.l + (y.l - x.l) * t, a: x.a + (y.a - x.a) * t, b: x.b + (y.b - x.b) * t).rgb
        }

        let surface = layer(5)
        let elevated = layer(10)
        let selection = mix(scheme.background, scheme[4], 0.3)
        let hover = scheme.foreground.hex + (dark ? "1a" : "14")
        let name = (wallpaper as NSString).lastPathComponent

        let tokens: [(String, String)] = [
            ("theme-format", "1"),
            ("theme-name", "\"tint\""),
            ("theme-author", "\"tint\""),
            ("theme-description", Escaping.json(String("Colours from \(name)".prefix(190)))),
            ("theme-appearance", dark ? "dark" : "light"),
            ("background-color", scheme.background.hex),
            ("surface-color", surface.hex),
            ("elevated-surface-color", elevated.hex),
            ("separator-color", mix(scheme.background, scheme[8], 0.5).hex),
            ("border-color", scheme[8].hex),
            ("text-color", scheme.foreground.hex),
            ("secondary-text-color", scheme[7].hex),
            ("muted-text-color", scheme[8].hex),
            ("link-color", scheme[4].hex),
            ("on-accent-color", scheme.background.hex),
            ("accent-color", scheme[4].hex),
            ("secondary-accent-color", scheme[5].hex),
            ("selection-color", selection.hex),
            ("hover-color", hover),
            ("success-color", scheme[2].hex),
            ("warning-color", scheme[3].hex),
            ("danger-color", scheme[1].hex),
            ("bar-color", surface.hex),
            ("bar-text-color", scheme.foreground.hex),
            ("bar-icon-color", scheme[7].hex),
            ("dock-indicator-color", scheme[4].hex),
            ("panel-color", surface.hex),
            ("card-color", elevated.hex),
            ("launcher-highlight-color", selection.hex),
            ("toast-color", scheme.foreground.hex),
            ("toast-text-color", scheme.background.hex),
        ]

        var css = "/* ApolloShell theme generated by tint from \(name.replacingAll("*/", with: "* /")).\n"
        css += "   Choose \"tint\" in Nexus → Themes once; tint rewrites this file on every change. */\n:root {\n"
        for (token, value) in tokens { css += "  --apollo-\(token): \(value);\n" }
        return css + "}\n"
    }

    /// Writes `tint.css` if ApolloShell is installed (its Application Support
    /// folder exists), creating the themes folder if needed.
    /// - Returns: the path written, or nil if ApolloShell isn't there.
    public static func write(_ scheme: Scheme, wallpaper: String, themesDirectory: String) throws -> String? {
        guard TintPaths.isDirectory((themesDirectory as NSString).deletingLastPathComponent) else { return nil }
        try FileManager.default.createDirectory(atPath: themesDirectory, withIntermediateDirectories: true)
        let path = themesDirectory + "/" + fileName
        try PywalWriter.atomicWrite(render(scheme, wallpaper: wallpaper), to: path)
        return path
    }
}
