import Foundation

/// Writes the files pywal writes to `~/.cache/wal`, in pywal's formats, so
/// everything that reads them — SketchyBar and JankyBorders configs, Neovim
/// (pywal.nvim), kitty, shell scripts — works with tint unchanged. Plus
/// tint's own Ghostty and WezTerm themes.
public enum PywalWriter {
    public struct Result: Sendable {
        public var written: [String]
        public var warnings: [String]
    }

    public static func write(_ scheme: Scheme, wallpaper: String, to cacheDirectory: String, templates: String?) throws -> Result {
        try FileManager.default.createDirectory(atPath: cacheDirectory, withIntermediateDirectories: true)
        var written: [String] = []
        var warnings: [String] = []

        func save(_ name: String, _ content: String) throws {
            let path = cacheDirectory + "/" + name
            try atomicWrite(content, to: path)
            written.append(path)
        }

        try save("wal", wallpaper)
        try save("colors", scheme.colors.map { $0.hex + "\n" }.joined())
        try save("colors.json", json(scheme, wallpaper))
        try save("colors.sh", shell(scheme, wallpaper))
        try save("colors.css", css(scheme, wallpaper))
        try save("colors-kitty.conf", kitty(scheme))
        try save("colors-wal.vim", vim(scheme, wallpaper))

        // Not pywal's: themes for the terminals tint reloads itself.
        try save("colors-ghostty", ghostty(scheme))
        try save("colors-wezterm.toml", wezterm(scheme))

        // User templates: ~/.config/wal/templates/<name> → ~/.cache/wal/<name>.
        if let templates, TintPaths.isDirectory(templates) {
            let names = try FileManager.default.contentsOfDirectory(atPath: templates).sorted()
            for name in names where !name.hasPrefix(".") {
                let path = templates + "/" + name
                guard !TintPaths.isDirectory(path), let template = try? String(contentsOfFile: path, encoding: .utf8) else { continue }
                let rendered = TemplateRenderer.render(template, scheme: scheme, wallpaper: wallpaper)
                try save(name, rendered.text)
                var seen = Set<String>()
                for token in rendered.unknown where seen.insert(token).inserted {
                    warnings.append("\(name): left \(token) as is (not a known placeholder)")
                }
            }
        }

        return Result(written: written, warnings: warnings)
    }

    /// Write to a temp file and rename over the target, so a program reading
    /// the file at the wrong moment sees the old or the new version, never half.
    static func atomicWrite(_ content: String, to path: String) throws {
        try Data(content.utf8).write(to: URL(fileURLWithPath: path), options: .atomic)
    }

    private static func numbered(_ scheme: Scheme) -> [(name: String, color: Rgb)] {
        scheme.colors.enumerated().map { ("color\($0.offset)", $0.element) }
    }

    static func json(_ scheme: Scheme, _ wallpaper: String) -> String {
        var s = "{\n"
        s += "  \"wallpaper\": \(Escaping.json(wallpaper)),\n"
        s += "  \"alpha\": \"100\",\n"
        s += "  \"special\": {\n"
        s += "    \"background\": \"\(scheme.background.hex)\",\n"
        s += "    \"foreground\": \"\(scheme.foreground.hex)\",\n"
        s += "    \"cursor\": \"\(scheme.cursor.hex)\"\n"
        s += "  },\n"
        s += "  \"colors\": {\n"
        s += numbered(scheme).map { "    \"\($0.name)\": \"\($0.color.hex)\"" }.joined(separator: ",\n")
        s += "\n  }\n}\n"
        return s
    }

    static func shell(_ scheme: Scheme, _ wallpaper: String) -> String {
        var s = "# Shell variables\n# Generated by tint (pywal-compatible)\n"
        s += "wallpaper='\(Escaping.shellSingleQuoted(wallpaper))'\n\n"
        s += "# Special\nbackground='\(scheme.background.hex)'\nforeground='\(scheme.foreground.hex)'\ncursor='\(scheme.cursor.hex)'\n\n"
        s += "# Colors\n"
        for (name, color) in numbered(scheme) { s += "\(name)='\(color.hex)'\n" }
        return s
    }

    static func css(_ scheme: Scheme, _ wallpaper: String) -> String {
        var s = "/* CSS variables\n   Generated by tint (pywal-compatible) */\n:root {\n"
        s += "    --wallpaper: url(\"\(Escaping.css(wallpaper))\");\n\n"
        s += "    /* Special */\n    --background: \(scheme.background.hex);\n    --foreground: \(scheme.foreground.hex);\n    --cursor: \(scheme.cursor.hex);\n\n"
        s += "    /* Colors */\n"
        for (name, color) in numbered(scheme) { s += "    --\(name): \(color.hex);\n" }
        return s + "}\n"
    }

    static func kitty(_ scheme: Scheme) -> String {
        let bg = scheme.background.hex, fg = scheme.foreground.hex
        var s = """
        foreground         \(fg)
        background         \(bg)
        cursor             \(scheme.cursor.hex)
        selection_foreground \(bg)
        selection_background \(fg)

        active_tab_foreground   \(bg)
        active_tab_background   \(fg)
        inactive_tab_foreground \(fg)
        inactive_tab_background \(bg)

        active_border_color   \(scheme[4].hex)
        inactive_border_color \(scheme[8].hex)
        bell_border_color     \(scheme[1].hex)


        """
        for (name, color) in numbered(scheme) { s += name.padding(toLength: 8, withPad: " ", startingAt: 0) + " \(color.hex)\n" }
        return s
    }

    static func vim(_ scheme: Scheme, _ wallpaper: String) -> String {
        var s = "\" Special\n"
        s += "let wallpaper  = \"\(Escaping.vim(wallpaper))\"\n"
        s += "let background = \"\(scheme.background.hex)\"\n"
        s += "let foreground = \"\(scheme.foreground.hex)\"\n"
        s += "let cursor     = \"\(scheme.cursor.hex)\"\n\n"
        s += "\" Colors\n"
        for (name, color) in numbered(scheme) { s += "let \(name.padding(toLength: 7, withPad: " ", startingAt: 0)) = \"\(color.hex)\"\n" }
        return s
    }

    /// A Ghostty theme; include it with `config-file = ~/.cache/wal/colors-ghostty`.
    static func ghostty(_ scheme: Scheme) -> String {
        var s = "# Ghostty theme, generated by tint\n"
        s += "background = \(scheme.background.hex)\n"
        s += "foreground = \(scheme.foreground.hex)\n"
        s += "cursor-color = \(scheme.cursor.hex)\n"
        s += "selection-background = \(scheme.foreground.hex)\n"
        s += "selection-foreground = \(scheme.background.hex)\n"
        for (i, color) in scheme.colors.enumerated() { s += "palette = \(i)=\(color.hex)\n" }
        return s
    }

    /// A WezTerm colour scheme, for `wezterm.color.load_scheme`.
    static func wezterm(_ scheme: Scheme) -> String {
        func list(_ colors: ArraySlice<Rgb>) -> String { colors.map { "\"\($0.hex)\"" }.joined(separator: ", ") }
        var s = "# WezTerm colour scheme, generated by tint\n[colors]\n"
        s += "foreground = \"\(scheme.foreground.hex)\"\n"
        s += "background = \"\(scheme.background.hex)\"\n"
        s += "cursor_bg = \"\(scheme.cursor.hex)\"\n"
        s += "cursor_fg = \"\(scheme.background.hex)\"\n"
        s += "cursor_border = \"\(scheme.cursor.hex)\"\n"
        s += "selection_bg = \"\(scheme.foreground.hex)\"\n"
        s += "selection_fg = \"\(scheme.background.hex)\"\n"
        s += "ansi = [\(list(scheme.colors[0..<8]))]\n"
        s += "brights = [\(list(scheme.colors[8..<16]))]\n\n"
        s += "[metadata]\nname = \"tint\"\n"
        return s
    }
}
